### Working with Data

In [1]:
import numpy as np
import pandas as pd

### CSV Files in Pandas

Download the iris dataset through the terminal. Make sure it is in the same folder as this notebook

In [3]:
# using read_csv
iris = pd.read_csv("iris.csv")
iris

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [5]:
# Head
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [7]:
# Writing DF to a csv file
iris.to_csv("iris_file_rewrite")

In [12]:
#group by splits your table into groups and then does a calculation on that group
#group the rows by species, then take the average of each column
iris.groupby("species").mean()

            sepal_length  sepal_width  petal_length  petal_width
species
setosa             5.006        3.418         1.464        0.244
versicolor         5.936        2.770         4.260        1.326
virginica          6.588        2.974         5.552        2.026

In [20]:
#Iterating through the DataFrame

# iterrows() hands us the table ONE ROW at a time, like flipping through flower cards
for i, row in iris.iterrows():
    # each loop gives us two things:
    #   i   = the row's label (0, then 1, then 2...)
    #   row = that whole row (a mini Series with all 5 columns)

    # pick one value from the row by its column name, then print it with the row number
    print(i, row["species"])   # e.g. 0 setosa

0 setosa
1 setosa
2 setosa
3 setosa
4 setosa
5 setosa
6 setosa
7 setosa
8 setosa
9 setosa
10 setosa
11 setosa
12 setosa
13 setosa
14 setosa
15 setosa
16 setosa
17 setosa
18 setosa
19 setosa
20 setosa
21 setosa
22 setosa
23 setosa
24 setosa
25 setosa
26 setosa
27 setosa
28 setosa
29 setosa
30 setosa
31 setosa
32 setosa
33 setosa
34 setosa
35 setosa
36 setosa
37 setosa
38 setosa
39 setosa
40 setosa
41 setosa
42 setosa
43 setosa
44 setosa
45 setosa
46 setosa
47 setosa
48 setosa
49 setosa
50 versicolor
51 versicolor
52 versicolor
53 versicolor
54 versicolor
55 versicolor
56 versicolor
57 versicolor
58 versicolor
59 versicolor
60 versicolor
61 versicolor
62 versicolor
63 versicolor
64 versicolor
65 versicolor
66 versicolor
67 versicolor
68 versicolor
69 versicolor
70 versicolor
71 versicolor
72 versicolor
73 versicolor
74 versicolor
75 versicolor
76 versicolor
77 versicolor
78 versicolor
79 versicolor
80 versicolor
81 versicolor
82 versicolor
83 versicolor
84 versicolor
85 versicolor
86 versicolor
87 versicolor
88 versicolor
89 versicolor
90 versicolor
91 versicolor
92 versicolor
93 versicolor
94 versicolor
95 versicolor
96 versicolor
97 versicolor
98 versicolor
99 versicolor
100 virginica
101 virginica
102 virginica
103 virginica
104 virginica
105 virginica
106 virginica
107 virginica
108 virginica
109 virginica
110 virginica
111 virginica
112 virginica
113 virginica
114 virginica
115 virginica
116 virginica
117 virginica
118 virginica
119 virginica
120 virginica
121 virginica
122 virginica
123 virginica
124 virginica
125 virginica
126 virginica
127 virginica
128 virginica
129 virginica
130 virginica
131 virginica
132 virginica
133 virginica
134 virginica
135 virginica
136 virginica
137 virginica
138 virginica
139 virginica
140 virginica
141 virginica
142 virginica
143 virginica
144 virginica
145 virginica
146 virginica
147 virginica
148 virginica
149 virginica

In [24]:
# Selecting multiple values when iterating:
for i, row in iris.iterrows():
    # double brackets = a list of column names, so we get several values back
    print(i, row[["species", "petal_length", "petal_width"]])

0 species         setosa
petal_length       1.4
petal_width        0.2
Name: 0, dtype: object
1 species         setosa
petal_length       1.4
petal_width        0.2
Name: 1, dtype: object
2 species         setosa
petal_length       1.3
petal_width        0.2
Name: 2, dtype: object
3 species         setosa
petal_length       1.5
petal_width        0.2
Name: 3, dtype: object
4 species         setosa
petal_length       1.4
petal_width        0.2
Name: 4, dtype: object
5 species         setosa
petal_length       1.7
petal_width        0.4
Name: 5, dtype: object
6 species         setosa
petal_length       1.4
petal_width        0.3
Name: 6, dtype: object
7 species         setosa
petal_length       1.5
petal_width        0.2
Name: 7, dtype: object
8 species         setosa
petal_length       1.4
petal_width        0.2
Name: 8, dtype: object
9 species         setosa
petal_length       1.5
petal_width        0.1
Name: 9, dtype: object
10 species         setosa
petal_length       1.5
petal_width        0.2
Name: 10, dtype: object
11 species         setosa
petal_length       1.6
petal_width        0.2
Name: 11, dtype: object
12 species         setosa
petal_length       1.4
petal_width        0.1
Name: 12, dtype: object
13 species         setosa
petal_length       1.1
petal_width        0.1
Name: 13, dtype: object
14 species         setosa
petal_length       1.2
petal_width        0.2
Name: 14, dtype: object
15 species         setosa
petal_length       1.5
petal_width        0.4
Name: 15, dtype: object
16 species         setosa
petal_length       1.3
petal_width        0.4
Name: 16, dtype: object
17 species         setosa
petal_length       1.4
petal_width        0.3
Name: 17, dtype: object
18 species         setosa
petal_length       1.7
petal_width        0.3
Name: 18, dtype: object
19 species         setosa
petal_length       1.5
petal_width        0.3
Name: 19, dtype: object
20 species         setosa
petal_length       1.7
petal_width        0.2
Name: 20, dtype: object
21 species         setosa
petal_length       1.5
petal_width        0.4
Name: 21, dtype: object
22 species         setosa
petal_length       1.0
petal_width        0.2
Name: 22, dtype: object
23 species         setosa
petal_length       1.7
petal_width        0.5
Name: 23, dtype: object
24 species         setosa
petal_length       1.9
petal_width        0.2
Name: 24, dtype: object
25 species         setosa
petal_length       1.6
petal_width        0.2
Name: 25, dtype: object
26 species         setosa
petal_length       1.6
petal_width        0.4
Name: 26, dtype: object
27 species         setosa
petal_length       1.5
petal_width        0.2
Name: 27, dtype: object
28 species         setosa
petal_length       1.4
petal_width        0.2
Name: 28, dtype: object
29 species         setosa
petal_length       1.6
petal_width        0.2
Name: 29, dtype: object
30 species         setosa
petal_length       1.6
petal_width        0.2
Name: 30, dtype: object
31 species         setosa
petal_length       1.5
petal_width        0.4
Name: 31, dtype: object
32 species         setosa
petal_length       1.5
petal_width        0.1
Name: 32, dtype: object
33 species         setosa
petal_length       1.4
petal_width        0.2
Name: 33, dtype: object
34 species         setosa
petal_length       1.5
petal_width        0.1
Name: 34, dtype: object
35 species         setosa
petal_length       1.2
petal_width        0.2
Name: 35, dtype: object
36 species         setosa
petal_length       1.3
petal_width        0.2
Name: 36, dtype: object
37 species         setosa
petal_length       1.5
petal_width        0.1
Name: 37, dtype: object
38 species         setosa
petal_length       1.3
petal_width        0.2
Name: 38, dtype: object
39 species         setosa
petal_length       1.5
petal_width        0.2
Name: 39, dtype: object
40 species         setosa
petal_length       1.3
petal_width        0.3
Name: 40, dtype: object
41 species         setosa
petal_length       1.3
petal_width        0.3
Name: 41, dtype: object
42 species         setosa
petal_length       1.3
petal_width        0.2
Name: 42, dtype: object
43 species         setosa
petal_length       1.6
petal_width        0.6
Name: 43, dtype: object
44 species         setosa
petal_length       1.9
petal_width        0.4
Name: 44, dtype: object
45 species         setosa
petal_length       1.4
petal_width        0.3
Name: 45, dtype: object
46 species         setosa
petal_length       1.6
petal_width        0.2
Name: 46, dtype: object
47 species         setosa
petal_length       1.4
petal_width        0.2
Name: 47, dtype: object
48 species         setosa
petal_length       1.5
petal_width        0.2
Name: 48, dtype: object
49 species         setosa
petal_length       1.4
petal_width        0.2
Name: 49, dtype: object
50 species         versicolor
petal_length           4.7
petal_width            1.4
Name: 50, dtype: object
51 species         versicolor
petal_length           4.5
petal_width            1.5
Name: 51, dtype: object
52 species         versicolor
petal_length           4.9
petal_width            1.5
Name: 52, dtype: object
53 species         versicolor
petal_length           4.0
petal_width            1.3
Name: 53, dtype: object
54 species         versicolor
petal_length           4.6
petal_width            1.5
Name: 54, dtype: object
55 species         versicolor
petal_length           4.5
petal_width            1.3
Name: 55, dtype: object
56 species         versicolor
petal_length           4.7
petal_width            1.6
Name: 56, dtype: object
57 species         versicolor
petal_length           3.3
petal_width            1.0
Name: 57, dtype: object
58 species         versicolor
petal_length           4.6
petal_width            1.3
Name: 58, dtype: object
59 species         versicolor
petal_length           3.9
petal_width            1.4
Name: 59, dtype: object
60 species         versicolor
petal_length           3.5
petal_width            1.0
Name: 60, dtype: object
61 species         versicolor
petal_length           4.2
petal_width            1.5
Name: 61, dtype: object
62 species         versicolor
petal_length           4.0
petal_width            1.0
Name: 62, dtype: object
63 species         versicolor
petal_length           4.7
petal_width            1.4
Name: 63, dtype: object
64 species         versicolor
petal_length           3.6
petal_width            1.3
Name: 64, dtype: object
65 species         versicolor
petal_length           4.4
petal_width            1.4
Name: 65, dtype: object
66 species         versicolor
petal_length           4.5
petal_width            1.5
Name: 66, dtype: object
67 species         versicolor
petal_length           4.1
petal_width            1.0
Name: 67, dtype: object
68 species         versicolor
petal_length           4.5
petal_width            1.5
Name: 68, dtype: object
69 species         versicolor
petal_length           3.9
petal_width            1.1
Name: 69, dtype: object
70 species         versicolor
petal_length           4.8
petal_width            1.8
Name: 70, dtype: object
71 species         versicolor
petal_length           4.0
petal_width            1.3
Name: 71, dtype: object
72 species         versicolor
petal_length           4.9
petal_width            1.5
Name: 72, dtype: object
73 species         versicolor
petal_length           4.7
petal_width            1.2
Name: 73, dtype: object
74 species         versicolor
petal_length           4.3
petal_width            1.3
Name: 74, dtype: object
75 species         versicolor
petal_length           4.4
petal_width            1.4
Name: 75, dtype: object
76 species         versicolor
petal_length           4.8
petal_width            1.4
Name: 76, dtype: object
77 species         versicolor
petal_length           5.0
petal_width            1.7
Name: 77, dtype: object
78 species         versicolor
petal_length           4.5
petal_width            1.5
Name: 78, dtype: object
79 species         versicolor
petal_length           3.5
petal_width            1.0
Name: 79, dtype: object
80 species         versicolor
petal_length           3.8
petal_width            1.1
Name: 80, dtype: object
81 species         versicolor
petal_length           3.7
petal_width            1.0
Name: 81, dtype: object
82 species         versicolor
petal_length           3.9
petal_width            1.2
Name: 82, dtype: object
83 species         versicolor
petal_length           5.1
petal_width            1.6
Name: 83, dtype: object
84 species         versicolor
petal_length           4.5
petal_width            1.5
Name: 84, dtype: object
85 species         versicolor
petal_length           4.5
petal_width            1.6
Name: 85, dtype: object
86 species         versicolor
petal_length           4.7
petal_width            1.5
Name: 86, dtype: object
87 species         versicolor
petal_length           4.4
petal_width            1.3
Name: 87, dtype: object
88 species         versicolor
petal_length           4.1
petal_width            1.3
Name: 88, dtype: object
89 species         versicolor
petal_length           4.0
petal_width            1.3
Name: 89, dtype: object
90 species         versicolor
petal_length           4.4
petal_width            1.2
Name: 90, dtype: object
91 species         versicolor
petal_length           4.6
petal_width            1.4
Name: 91, dtype: object
92 species         versicolor
petal_length           4.0
petal_width            1.2
Name: 92, dtype: object
93 species         versicolor
petal_length           3.3
petal_width            1.0
Name: 93, dtype: object
94 species         versicolor
petal_length           4.2
petal_width            1.3
Name: 94, dtype: object
95 species         versicolor
petal_length           4.2
petal_width            1.2
Name: 95, dtype: object
96 species         versicolor
petal_length           4.2
petal_width            1.3
Name: 96, dtype: object
97 species         versicolor
petal_length           4.3
petal_width            1.3
Name: 97, dtype: object
98 species         versicolor
petal_length           3.0
petal_width            1.1
Name: 98, dtype: object
99 species         versicolor
petal_length           4.1
petal_width            1.3
Name: 99, dtype: object
100 species         virginica
petal_length          6.0
petal_width           2.5
Name: 100, dtype: object
101 species         virginica
petal_length          5.1
petal_width           1.9
Name: 101, dtype: object
102 species         virginica
petal_length          5.9
petal_width           2.1
Name: 102, dtype: object
103 species         virginica
petal_length          5.6
petal_width           1.8
Name: 103, dtype: object
104 species         virginica
petal_length          5.8
petal_width           2.2
Name: 104, dtype: object
105 species         virginica
petal_length          6.6
petal_width           2.1
Name: 105, dtype: object
106 species         virginica
petal_length          4.5
petal_width           1.7
Name: 106, dtype: object
107 species         virginica
petal_length          6.3
petal_width           1.8
Name: 107, dtype: object
108 species         virginica
petal_length          5.8
petal_width           1.8
Name: 108, dtype: object
109 species         virginica
petal_length          6.1
petal_width           2.5
Name: 109, dtype: object
110 species         virginica
petal_length          5.1
petal_width           2.0
Name: 110, dtype: object
111 species         virginica
petal_length          5.3
petal_width           1.9
Name: 111, dtype: object
112 species         virginica
petal_length          5.5
petal_width           2.1
Name: 112, dtype: object
113 species         virginica
petal_length          5.0
petal_width           2.0
Name: 113, dtype: object
114 species         virginica
petal_length          5.1
petal_width           2.4
Name: 114, dtype: object
115 species         virginica
petal_length          5.3
petal_width           2.3
Name: 115, dtype: object
116 species         virginica
petal_length          5.5
petal_width           1.8
Name: 116, dtype: object
117 species         virginica
petal_length          6.7
petal_width           2.2
Name: 117, dtype: object
118 species         virginica
petal_length          6.9
petal_width           2.3
Name: 118, dtype: object
119 species         virginica
petal_length          5.0
petal_width           1.5
Name: 119, dtype: object
120 species         virginica
petal_length          5.7
petal_width           2.3
Name: 120, dtype: object
121 species         virginica
petal_length          4.9
petal_width           2.0
Name: 121, dtype: object
122 species         virginica
petal_length          6.7
petal_width           2.0
Name: 122, dtype: object
123 species         virginica
petal_length          4.9
petal_width           1.8
Name: 123, dtype: object
124 species         virginica
petal_length          5.7
petal_width           2.1
Name: 124, dtype: object
125 species         virginica
petal_length          6.0
petal_width           1.8
Name: 125, dtype: object
126 species         virginica
petal_length          4.8
petal_width           1.8
Name: 126, dtype: object
127 species         virginica
petal_length          4.9
petal_width           1.8
Name: 127, dtype: object
128 species         virginica
petal_length          5.6
petal_width           2.1
Name: 128, dtype: object
129 species         virginica
petal_length          5.8
petal_width           1.6
Name: 129, dtype: object
130 species         virginica
petal_length          6.1
petal_width           1.9
Name: 130, dtype: object
131 species         virginica
petal_length          6.4
petal_width           2.0
Name: 131, dtype: object
132 species         virginica
petal_length          5.6
petal_width           2.2
Name: 132, dtype: object
133 species         virginica
petal_length          5.1
petal_width           1.5
Name: 133, dtype: object
134 species         virginica
petal_length          5.6
petal_width           1.4
Name: 134, dtype: object
135 species         virginica
petal_length          6.1
petal_width           2.3
Name: 135, dtype: object
136 species         virginica
petal_length          5.6
petal_width           2.4
Name: 136, dtype: object
137 species         virginica
petal_length          5.5
petal_width           1.8
Name: 137, dtype: object
138 species         virginica
petal_length          4.8
petal_width           1.8
Name: 138, dtype: object
139 species         virginica
petal_length          5.4
petal_width           2.1
Name: 139, dtype: object
140 species         virginica
petal_length          5.6
petal_width           2.4
Name: 140, dtype: object
141 species         virginica
petal_length          5.1
petal_width           2.3
Name: 141, dtype: object
142 species         virginica
petal_length          5.1
petal_width           1.9
Name: 142, dtype: object
143 species         virginica
petal_length          5.9
petal_width           2.3
Name: 143, dtype: object
144 species         virginica
petal_length          5.7
petal_width           2.5
Name: 144, dtype: object
145 species         virginica
petal_length          5.2
petal_width           2.3
Name: 145, dtype: object
146 species         virginica
petal_length          5.0
petal_width           1.9
Name: 146, dtype: object
147 species         virginica
petal_length          5.2
petal_width           2.0
Name: 147, dtype: object
148 species         virginica
petal_length          5.4
petal_width           2.3
Name: 148, dtype: object
149 species         virginica
petal_length          5.1
petal_width           1.8
Name: 149, dtype: object

In [25]:
# Using Describe()
iris.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [28]:
#Ranking petal length in asc order:

iris["Rank Petal Length"] = iris["petal_length"].rank(ascending=0)
iris

,sepal_length,sepal_width,petal_length,petal_width,species,Rank Petal Length
0,5.1,3.5,1.4,0.2,setosa,133.5
1,4.9,3.0,1.4,0.2,setosa,133.5
2,4.7,3.2,1.3,0.2,setosa,143.0
3,4.6,3.1,1.5,0.2,setosa,120.5
4,5.0,3.6,1.4,0.2,setosa,133.5
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica,33.5
146,6.3,2.5,5.0,1.9,virginica,44.5
147,6.5,3.0,5.2,2.0,virginica,33.5
148,6.2,3.4,5.4,2.3,virginica,29.5
149,5.9,3.0,5.1,1.8,virginica,38.5

In [29]:
iris.groupby("species").mean()

,sepal_length,sepal_width,petal_length,petal_width,Rank Petal Length
species,,,,,
setosa,5.006,3.418,1.464,0.244,125.50
versicolor,5.936,2.770,4.260,1.326,74.61
virginica,6.588,2.974,5.552,2.026,26.39

In [34]:
#Creating a new DataFrame for each species

# Make a new table for each species by keeping only the matching rows
# iris["species"] == "setosa" gives True/False for every row, iris[...] keeps the True ones
setosa = iris[iris["species"] == "setosa"]
versicolor = iris[iris["species"] == "versicolor"]
virginica = iris[iris["species"] == "virginica"]

# Show the first 5 rows of the virginica table
virginica.head()

,sepal_length,sepal_width,petal_length,petal_width,species,Rank Petal Length
100,6.3,3.3,6.0,2.5,virginica,10.5
101,5.8,2.7,5.1,1.9,virginica,38.5
102,7.1,3.0,5.9,2.1,virginica,12.5
103,6.3,2.9,5.6,1.8,virginica,22.5
104,6.5,3.0,5.8,2.2,virginica,15.0

In [37]:
#Creating sepal and petal info from iris
sepal_info = iris[["sepal_length", "sepal_width", "species"]]
petal_info = iris[["petal_length", "petal_width", "species"]]
sepal_info.head()

   sepal_length  sepal_width species
0           5.1          3.5  setosa
1           4.9          3.0  setosa
2           4.7          3.2  setosa
3           4.6          3.1  setosa
4           5.0          3.6  setosa

In [39]:
#Loading a Json into a dataframe
iris_json = pd.read_json("iris.json")
iris_json.head()

   sepalLength  sepalWidth  petalLength  petalWidth species
0          5.1         3.5          1.4         0.2  setosa
1          4.9         3.0          1.4         0.2  setosa
2          4.7         3.2          1.3         0.2  setosa
3          4.6         3.1          1.5         0.2  setosa
4          5.0         3.6          1.4         0.2  setosa

In [51]:
# Merging sepal_info and petal_info
# Join the two tables side by side, matching rows that have the same species
mergedDF = pd.merge(sepal_info, petal_info, on = "species")
mergedDF.head()

   sepal_length  sepal_width species  petal_length  petal_width
0           5.1          3.5  setosa           1.4          0.2
1           5.1          3.5  setosa           1.4          0.2
2           5.1          3.5  setosa           1.3          0.2
3           5.1          3.5  setosa           1.5          0.2
4           5.1          3.5  setosa           1.4          0.2

In [50]:
# concat glues tables together. It doesn’t match anything, it just sticks them in a line.
# essentially stacks dataframes
# Stack petal_info underneath sepal_info (adds rows, one table on top of the other)
stacked = pd.concat([sepal_info, petal_info])
stacked

     sepal_length  sepal_width    species  petal_length  petal_width
0             5.1          3.5     setosa           NaN          NaN
1             4.9          3.0     setosa           NaN          NaN
2             4.7          3.2     setosa           NaN          NaN
3             4.6          3.1     setosa           NaN          NaN
4             5.0          3.6     setosa           NaN          NaN
..            ...          ...        ...           ...          ...
145           NaN          NaN  virginica           5.2          2.3
146           NaN          NaN  virginica           5.0          1.9
147           NaN          NaN  virginica           5.2          2.0
148           NaN          NaN  virginica           5.4          2.3
149           NaN          NaN  virginica           5.1          1.8

[300 rows x 5 columns]